// Code generated by MockGen. DO NOT EDIT.
// Source: ssm.go
//
// Generated by this command:
//
//	mockgen -source=ssm.go -package=mock -destination=./mock/ssm_mock.go
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	gomock "go.uber.org/mock/gomock"
)

// MockSSM is a mock of SSM interface.
type MockSSM struct {
	ctrl     *gomock.Controller
	recorder *MockSSMMockRecorder
}

// MockSSMMockRecorder is the mock recorder for MockSSM.
type MockSSMMockRecorder struct {
	mock *MockSSM
}

// NewMockSSM creates a new mock instance.
func NewMockSSM(ctrl *gomock.Controller) *MockSSM {
	mock := &MockSSM{ctrl: ctrl}
	mock.recorder = &MockSSMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSM) EXPECT() *MockSSMMockRecorder {
	return m.recorder
}

// StartSession mocks base method.
func (m *MockSSM) StartSession(ctx context.Context, params *ssm.StartSessionInput, optFns ...func(*ssm.Options)) (*ssm.StartSessionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartSession", varargs...)
	ret0, _ := ret[0].(*ssm.StartSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSession indicates an expected call of StartSession.
func (mr *MockSSMMockRecorder) StartSession(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockSSM)(nil).StartSession), varargs...)
}
