before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - <<: &build_defaults
      binary: bin/aws-ssh
      main: ./cmd/main.go
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: 'aws-ssh_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'BREAKING CHANGE'
      regexp: "(^.*!feat[(\\w)]*:+.*$)|(^.*fix[(\\w)]*:+.*$)"
      order: 0
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999

checksum:
  name_template: 'checksums.txt'