before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - <<: &build_defaults
      binary: bin/name
      main: ./cmd/name
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [386, amd64, arm64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: 'name_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    replacements:
      darwin: macOS
    format: tar.gz
    files:
      - LICENSE
  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'