# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsh < Formula
  desc "How engineers learn about CLIs"
  homepage "https://github.com/kikyomits/aws-ssh"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kikyomits/aws-ssh/releases/download/0.0.1/aws-ssh_0.0.1_darwin_arm64.tar.gz"
      sha256 "94877bcba9fbe36cfbd0528f0b55223cc68bdd0e43dac6c3fc18b9b32a4ca00e"

      def install
        bin.install "bin/aws-ssh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kikyomits/aws-ssh/releases/download/0.0.1/aws-ssh_0.0.1_darwin_amd64.tar.gz"
      sha256 "5d292816052fd36e9e33207fa69d76e5655c58c673309d53bd6dbf87abb98bfb"

      def install
        bin.install "bin/aws-ssh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kikyomits/aws-ssh/releases/download/0.0.1/aws-ssh_0.0.1_linux_amd64.tar.gz"
      sha256 "1440ec7fdacb10147800c2497228c85c1e03f54e074d139e449b638adc5c917d"

      def install
        bin.install "bin/aws-ssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kikyomits/aws-ssh/releases/download/0.0.1/aws-ssh_0.0.1_linux_arm64.tar.gz"
      sha256 "226eceeeb88d25d3c69a2f61cb572c4bca436cf851991c2038d7004b5302eb90"

      def install
        bin.install "bin/aws-ssh"
      end
    end
  end
end
