// Code generated by MockGen. DO NOT EDIT.
// Source: port_forward.go
//
// Generated by this command:
//
//	mockgen -source=port_forward.go -package=mock -destination=./mock/port_forward_mock.go
//
// Package mock is a generated GoMock package.
package mock
