name: PKG CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOLANG_VERSION: 1.21.1

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - uses: actions/checkout@v3
      - name: "Run unit tests"
        run: make test-ci
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: |
            coverage.out
            tests.out
#  lint:
#    name: "Lint"
#    runs-on: ubuntu-latest
#    steps:
#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: ${{ env.GOLANG_VERSION }}
#    - uses: actions/checkout@v3
#    - name: "Run lint"
#      run: make lint

  compile:
#    needs: [ test, lint ]
    needs: [test]
    name: "Compile"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - uses: actions/checkout@v2
      - name: "Compile executable"
        run: make compile
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1